
services:
    backend:
        build: ./x-admin
        container_name: x-admin
        ports:
            - "9999:9999"
        volumes:
            - ./x-admin/logs:/app/logs
        environment:
            SERVER_PORT: 9999
            SPRING_DATASOURCE_URL: jdbc:mysql://mysql6.sqlpub.com:3311/project_xdb?useSSL=true&requireSSL=true
            SPRING_DATASOURCE_USERNAME: youzilite
            SPRING_DATASOURCE_PASSWORD: vsNDgmYmYPyDRkUM
        networks:
            - x_net
    frontend:
        build: ./web-vue3
        container_name: web-vue3
        ports:
            - "80:80"
        volumes:
            - ./web-vue3/logs:/var/log/nginx
        networks:
            - x_net
networks:
    x_net:
        driver: bridge
        