# 数据路径
path: ""  # dataset root dir
train:
  - "E:/HaGRID/call/call/train.txt"
  - "E:/HaGRID/dislike/dislike/train.txt"
  - "E:/HaGRID/fist/fist/train.txt"
  - "E:/HaGRID/four/four/train.txt"
  - "E:/HaGRID/like/like/train.txt"
  - "E:/HaGRID/mute/mute/train.txt"
  - "E:/HaGRID/ok/ok/train.txt"
  - "E:/HaGRID/one/one/train.txt"
  - "E:/HaGRID/palm/palm/train.txt"
  - "E:/HaGRID/peace/peace/train.txt"
  - "E:/HaGRID/peace_inverted/peace_inverted/train.txt"
  - "E:/HaGRID/rock/rock/train.txt"
  - "E:/HaGRID/stop/stop/train.txt"
  - "E:/HaGRID/stop_inverted/stop_inverted/train.txt"
  - "E:/HaGRID/three/three/train.txt"
  - "E:/HaGRID/three2/three2/train.txt"
  - "E:/HaGRID/two_up/two_up/train.txt"
  - "E:/HaGRID/two_up_inverted/two_up_inverted/train.txt"

val:
  - "E:/HaGRID/call/call/val.txt"
  - "E:/HaGRID/dislike/dislike/val.txt"
  - "E:/HaGRID/fist/fist/val.txt"
  - "E:/HaGRID/four/four/val.txt"
  - "E:/HaGRID/like/like/val.txt"
  - "E:/HaGRID/mute/mute/val.txt"
  - "E:/HaGRID/ok/ok/val.txt"
  - "E:/HaGRID/one/one/val.txt"
  - "E:/HaGRID/palm/palm/val.txt"
  - "E:/HaGRID/peace/peace/val.txt"
  - "E:/HaGRID/peace_inverted/peace_inverted/val.txt"
  - "E:/HaGRID/rock/rock/val.txt"
  - "E:/HaGRID/stop/stop/val.txt"
  - "E:/HaGRID/stop_inverted/stop_inverted/val.txt"
  - "E:/HaGRID/three/three/val.txt"
  - "E:/HaGRID/three2/three2/val.txt"
  - "E:/HaGRID/two_up/two_up/val.txt"
  - "E:/HaGRID/two_up_inverted/two_up_inverted/val.txt"

test:  # test images (optional)
data_type: voc

# Classes
nc: 19  # number of classes
names: { 'one': 0, 'two_up': 1, 'two_up_inverted': 2, 'three': 3, 'three2': 4,
         'four': 5, 'fist': 6, 'palm': 7, 'ok': 8, 'peace': 9,
         'peace_inverted': 10, 'like': 11, 'dislike': 12, 'stop': 13, 'stop_inverted': 14,
         'call': 15, 'mute': 16, 'rock': 17, 'no_gesture': 18 }
