server:
  port: 9999
spring:
  datasource:
    #默认
    username: root
    password: 123456
    url: jdbc:mysql://localhost/xdb?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      port: 6379
      host: localhost


logging:
  level:
    com.diy: debug

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-not-delete-value: 0
      logic-delete-value: 1
  type-aliases-package: com.diy.*.entity

cloudflare:
  r2:
    access-key: "71b2b4aef9d416917801610b1dc33963"
    secret-key: "7d33aa0640e631cbd49731633328c2f5c436b555989b1ac2f4002424cae492be"
    endpoint: "https://4b9f4af50152c4c4b85005817e83e269.r2.cloudflarestorage.com"
    bucket-name: "avatar-bucket"
    domain: "https://avatar.youzilite.us.kg" # 你绑定的访问域名